In [6]:
import tensorflow as tf

In [28]:
import numpy as np

In [2]:
hello = tf.constant("hello world")

In [3]:
sess = tf.Session()

In [8]:
#notes

In [ ]:
print(sess.run(hello))

# sdbaknl

$e^{i\pi} + 1 = 0$

In [9]:
s = 'haii'

In [10]:
s.capitalize

<function str.capitalize()>

In [11]:
s.capitalize()

'Haii'

In [12]:
s.casefold()

'haii'

In [27]:
s.center(80)

'                                      haii                                      '

In [30]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
arr = np.linspace(0,150,200)

In [35]:
arr[4]

3.0150753768844223

In [53]:
np.random.randint(2,10,(3,3))

array([[2, 7, 3],
       [4, 4, 2],
       [4, 8, 5]])

In [56]:
arr.prod()

0.0

In [57]:
arr

array([  0.        ,   0.75376884,   1.50753769,   2.26130653,
         3.01507538,   3.76884422,   4.52261307,   5.27638191,
         6.03015075,   6.7839196 ,   7.53768844,   8.29145729,
         9.04522613,   9.79899497,  10.55276382,  11.30653266,
        12.06030151,  12.81407035,  13.5678392 ,  14.32160804,
        15.07537688,  15.82914573,  16.58291457,  17.33668342,
        18.09045226,  18.84422111,  19.59798995,  20.35175879,
        21.10552764,  21.85929648,  22.61306533,  23.36683417,
        24.12060302,  24.87437186,  25.6281407 ,  26.38190955,
        27.13567839,  27.88944724,  28.64321608,  29.39698492,
        30.15075377,  30.90452261,  31.65829146,  32.4120603 ,
        33.16582915,  33.91959799,  34.67336683,  35.42713568,
        36.18090452,  36.93467337,  37.68844221,  38.44221106,
        39.1959799 ,  39.94974874,  40.70351759,  41.45728643,
        42.21105528,  42.96482412,  43.71859296,  44.47236181,
        45.22613065,  45.9798995 ,  46.73366834,  47.48