In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.14.0


In [4]:
hello = tf.constant("hello ")

In [5]:
linjo = tf.constant("Linjo")

In [6]:
with tf.Session() as sess:
    result = sess.run(hello + linjo)

In [7]:
print(result)

b'hello Linjo'


In [10]:
myzero = tf.zeros((4,4))

In [27]:
myrandn = tf.random_normal((4,4),mean = 0,stddev = 1)

In [19]:
myops = [myzero,myrandn]

In [18]:
with tf.Session()as sess:
    result = sess.run(myzero + myrandn)
    print(result)

[[-2.119813    1.566161   -0.01806277 -0.3510278 ]
 [-1.2730474  -1.0102768   0.3546607   0.43209127]
 [-0.36968723  0.2627461   0.10351697  1.7749655 ]
 [-0.20146312 -0.14044636 -0.3911887  -1.362554  ]]


In [28]:
for op in myops:
    print(tf.Session().run(op))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[-0.89566386  0.78438795 -0.7219929   1.4717417 ]
 [-0.7445455  -1.9010931   0.0153885  -0.50813115]
 [ 0.81698     0.7324581  -1.52936     0.3969848 ]
 [ 0.35727796 -0.86678624 -0.5951777   0.46170563]]
