In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.14.0


In [4]:
hello = tf.constant("Hello ")
world = tf.constant("World")

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [7]:
print(result)

b'Hello World'


In [8]:
a = tf.constant(1)
b = tf.constant(5)

In [9]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [10]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [11]:
result

6

In [12]:
c = tf.constant(10)

In [13]:
mat = tf.fill((4,4),10)

In [31]:
with tf.Session() as sess:
    print(sess.run(mat))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [32]:
mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [33]:
myzeros = tf.zeros((4,4))

In [34]:
myones = tf.ones((4,4))

In [35]:
myrandn = tf.random_normal((4,4))

In [36]:
myrandu = tf.random_uniform((4,4))

In [37]:
myops = [c,mat,myzeros,myones,myrandn,myrandu]

In [38]:
sess = tf.InteractiveSession()

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [28]:
for op in myops:
    print(sess.run(op),'\n')

10 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[ 0.9691904  -0.13725731  0.874486   -0.06753086]
 [ 0.9123894  -0.56651586 -0.84088296 -1.2226316 ]
 [ 0.08339044  0.7894147  -0.42335072  1.1020082 ]
 [ 1.480259    0.44474536 -2.2080476   0.09470028]] 

[[0.31655407 0.8257406  0.48758698 0.23147273]
 [0.9680685  0.11534488 0.2942953  0.17728078]
 [0.01439297 0.44052005 0.6672038  0.3596053 ]
 [0.5204307  0.6711912  0.5719713  0.43008518]] 



In [39]:
for op in myops:
    print(op.eval(),'\n')

10 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[-1.1443366  -0.28414702 -0.71467674 -1.3290819 ]
 [-0.7852974   0.2117512   0.9489412  -1.4477689 ]
 [-2.409902    2.3693898   1.0422201  -0.6515943 ]
 [-0.8183372   0.95140594 -1.9489032  -1.8800367 ]] 

[[0.8865862  0.629519   0.04726875 0.07731915]
 [0.33737326 0.20989871 0.0487175  0.17251754]
 [0.7109705  0.7183192  0.69159937 0.6706053 ]
 [0.61225975 0.06062031 0.20400894 0.90162766]] 

